/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Container
 */
export interface Container {
  /**
   *
   * @type {number}
   * @memberof Container
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Container
   */
  dockerId: string;
  /**
   *
   * @type {string}
   * @memberof Container
   */
  image: string;
}

/**
 * Check if a given object implements the Container interface.
 */
export function instanceOfContainer(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'dockerId' in value;
  isInstance = isInstance && 'image' in value;

  return isInstance;
}

export function ContainerFromJSON(json: any): Container {
  return ContainerFromJSONTyped(json, false);
}

export function ContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Container {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    dockerId: json['dockerId'],
    image: json['image'],
  };
}

export function ContainerToJSON(value?: Container | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    dockerId: value.dockerId,
    image: value.image,
  };
}
