/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DbContainerId
 */
export interface DbContainerId {
  /**
   *
   * @type {number}
   * @memberof DbContainerId
   */
  dbContainerId: number;
}

/**
 * Check if a given object implements the DbContainerId interface.
 */
export function instanceOfDbContainerId(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dbContainerId' in value;

  return isInstance;
}

export function DbContainerIdFromJSON(json: any): DbContainerId {
  return DbContainerIdFromJSONTyped(json, false);
}

export function DbContainerIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbContainerId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dbContainerId: json['dbContainerId'],
  };
}

export function DbContainerIdToJSON(value?: DbContainerId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dbContainerId: value.dbContainerId,
  };
}
