/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface V1ContainerAllGet200ResponseInner
 */
export interface V1ContainerAllGet200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof V1ContainerAllGet200ResponseInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof V1ContainerAllGet200ResponseInner
     */
    dockerId: string;
    /**
     * 
     * @type {string}
     * @memberof V1ContainerAllGet200ResponseInner
     */
    image: string;
}

/**
 * Check if a given object implements the V1ContainerAllGet200ResponseInner interface.
 */
export function instanceOfV1ContainerAllGet200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "dockerId" in value;
    isInstance = isInstance && "image" in value;

    return isInstance;
}

export function V1ContainerAllGet200ResponseInnerFromJSON(json: any): V1ContainerAllGet200ResponseInner {
    return V1ContainerAllGet200ResponseInnerFromJSONTyped(json, false);
}

export function V1ContainerAllGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ContainerAllGet200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dockerId': json['dockerId'],
        'image': json['image'],
    };
}

export function V1ContainerAllGet200ResponseInnerToJSON(value?: V1ContainerAllGet200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dockerId': value.dockerId,
        'image': value.image,
    };
}

