/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1LoginPostRequest
 */
export interface V1LoginPostRequest {
  /**
   *
   * @type {string}
   * @memberof V1LoginPostRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof V1LoginPostRequest
   */
  password: string;
}

/**
 * Check if a given object implements the V1LoginPostRequest interface.
 */
export function instanceOfV1LoginPostRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'password' in value;

  return isInstance;
}

export function V1LoginPostRequestFromJSON(json: any): V1LoginPostRequest {
  return V1LoginPostRequestFromJSONTyped(json, false);
}

export function V1LoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1LoginPostRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function V1LoginPostRequestToJSON(value?: V1LoginPostRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
