/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';

/**
 * 
 * @export
 * @interface V1UserNewPost200Response
 */
export interface V1UserNewPost200Response {
    /**
     * 
     * @type {number}
     * @memberof V1UserNewPost200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof V1UserNewPost200Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserNewPost200Response
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserNewPost200Response
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserNewPost200Response
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the V1UserNewPost200Response interface.
 */
export function instanceOfV1UserNewPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UserNewPost200ResponseFromJSON(json: any): V1UserNewPost200Response {
    return V1UserNewPost200ResponseFromJSONTyped(json, false);
}

export function V1UserNewPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UserNewPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function V1UserNewPost200ResponseToJSON(value?: V1UserNewPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'password': value.password,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

