/* tslint:disable */
/* eslint-disable */
/**
 * Dockops-board API specification
 * Dockops-board is an open source manager for docker containers with web UI
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface V1UserNewPostRequest
 */
export interface V1UserNewPostRequest {
  /**
   *
   * @type {string}
   * @memberof V1UserNewPostRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof V1UserNewPostRequest
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof V1UserNewPostRequest
   */
  githubToken?: string;
}

/**
 * Check if a given object implements the V1UserNewPostRequest interface.
 */
export function instanceOfV1UserNewPostRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'password' in value;

  return isInstance;
}

export function V1UserNewPostRequestFromJSON(json: any): V1UserNewPostRequest {
  return V1UserNewPostRequestFromJSONTyped(json, false);
}

export function V1UserNewPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UserNewPostRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    githubToken: !exists(json, 'githubToken') ? undefined : json['githubToken'],
  };
}

export function V1UserNewPostRequestToJSON(value?: V1UserNewPostRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    githubToken: value.githubToken,
  };
}
